spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home42_Students
    password: 123456
    username: IgorSQL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  mvc:
#    view:
#      prefix: pages/
#      suffix: .jsp
#management:
#  endpoints:
#    web:
#     exposure:
#        include: '*'